### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/appstore-connect-jwt-token-generator-core - Not found

### ISSUE THREAD

**Issue by DreamPWJ** [poad/appstore-connect-jwt-generator-core#584]
PS D:\repo\jenkins-shared-library\_jenkins\web\app-store> npm install appstore-connect-jwt-token-generator-core
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/appstore-connect-jwt-token-generator-core - Not found
npm ERR! 404
npm ERR! 404  'appstore-connect-jwt-token-generator-core@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2022-01-14T08_22_43_599Z-debug.log

**Comment by poad** [comment]
@DreamPWJ 
Thanks for the report. I will look into the cause of this problem.

**Comment by poad** [comment]
@DreamPWJ 
It seems to be a mistake in the documentation.
Please run `npm i appstore-connect-jwt-generator-core`.


```sh
$ npm i appstore-connect-jwt-generator-core

added 31 packages, and audited 32 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ cat package.json 
{
  "dependencies": {
    "appstore-connect-jwt-generator-core": "^1.1.4"
  }
}
$ 
```
